"use client";

import {
  ArrowRight,
  Broadcast,
  ChartLineUp,
  ClockAfternoon,
  Cpu,
  MapTrifold,
  NavigationArrow,
  Pulse,
  ShieldCheck,
  UserCheck,
  WarningOctagon,
} from "@phosphor-icons/react/dist/ssr";
import { Reveal, revealItem } from "../reveal";
import { useQuote } from "../quote-modal";
import { btn, btnHero, btnSolid, cx, label } from "../ui";

interface FeatureItem {
  icon: React.ElementType;
  category: string;
  title: string;
  desc: string;
  badge: string;
}

const ROW_1_FEATURES: FeatureItem[] = [
  {
    icon: Broadcast,
    category: "Telemetry",
    title: "GPS Tracking on Trucks & Trailers",
    desc: "Real-time GPS tracking for complete visibility of your fleet and cargo.",
    badge: "Dual-Asset Hardware",
  },
  {
    icon: ShieldCheck,
    category: "Safety",
    title: "Truck Safety Features",
    desc: "State-of-the-art safety equipment and monitoring systems on all vehicles.",
    badge: "Detroit Assurance 5.0",
  },
  {
    icon: NavigationArrow,
    category: "Automation",
    title: "Automatic Load Status Updates",
    desc: "Receive automatic status messages generated by geofencing technology for peace of mind.",
    badge: "Geofenced Webhooks",
  },
  {
    icon: Pulse,
    category: "Platform",
    title: "Customer Active Loads",
    desc: "Interactive map showing all your loads in real time for complete transparency.",
    badge: "24/7 Portal Access",
  },
  {
    icon: ChartLineUp,
    category: "Analytics",
    title: "Historical Load Intelligence",
    desc: "Access comprehensive data for all your loads to improve logistics decisions.",
    badge: "Verified 99.2% SLA",
  },
];

const ROW_2_FEATURES: FeatureItem[] = [
  {
    icon: MapTrifold,
    category: "Routing",
    title: "Route Optimization",
    desc: "Advanced routing algorithms to ensure the most efficient delivery paths.",
    badge: "Doppler Weather AI",
  },
  {
    icon: UserCheck,
    category: "Support",
    title: "One-Point Contact for Customers",
    desc: "Dedicated account representative for seamless communication and support.",
    badge: "Dedicated Desk Lead",
  },
  {
    icon: ClockAfternoon,
    category: "Planning",
    title: "Load Planning in Advance",
    desc: "Plan and schedule loads ahead of time for better logistics coordination.",
    badge: "100% Contract Backed",
  },
  {
    icon: WarningOctagon,
    category: "Monitoring",
    title: "Sitting Truck Alerts",
    desc: "Automatic notifications when trucks are idle to maximize fleet efficiency.",
    badge: "30m Alert Trigger",
  },
  {
    icon: Cpu,
    category: "Integration",
    title: "Direct EDI & API Connectivity",
    desc: "Instant bi-directional load tendering, shipment tracking, and electronic freight invoicing.",
    badge: "EDI 204 / 214 / 210",
  },
];

function FeatureCard({ feature }: { feature: FeatureItem }) {
  const Icon = feature.icon;

  return (
    <div className="group/card w-[340px] sm:w-[380px] h-[220px] shrink-0 bg-surface border border-line p-6 flex flex-col justify-between transition-all duration-200 hover:border-azure hover:shadow-md">
      <div>
        <div className="flex items-center justify-between pb-3 border-b border-line">
          <div className="flex items-center gap-2.5">
            <div className="size-8 rounded-full bg-azure/10 text-azure flex items-center justify-center group-hover/card:bg-azure group-hover/card:text-white transition-colors duration-200">
              <Icon size={17} weight="bold" />
            </div>
            <span
              className={cx(
                label,
                "text-[10px] text-soft-text group-hover/card:text-azure transition-colors duration-200",
              )}
            >
              {feature.category}
            </span>
          </div>
          <span className="font-mono text-[10.5px] text-azure font-medium">
            {feature.badge}
          </span>
        </div>

        <h3 className="font-display text-[16.5px] font-bold text-ink-text mt-3.5 mb-1.5 leading-snug tracking-[-0.01em]">
          {feature.title}
        </h3>
        <p className="text-[13.5px] leading-[1.58] text-body-text m-0 line-clamp-3">
          {feature.desc}
        </p>
      </div>

      <div className="pt-3 border-t border-line/60 flex items-center justify-between text-[11px] font-mono text-soft-text">
        <span className="group-hover/card:text-azure transition-colors duration-200 flex items-center gap-1.5">
          <span className="size-1.5 rounded-full bg-azure" />
          Enterprise Standard
        </span>
        <span className="text-mute-2">Hover to pause</span>
      </div>
    </div>
  );
}

/**
 * Industry-Leading Features Section.
 *
 * Sits on a 100% light field (bg-page) following the ShipOpenRoad section.
 *
 * Implements a dual-tier continuous scrolling marquee of capability cards,
 * mirroring the live site's proven UX while elevating it with PKT Group's
 * crisp zero-radius architecture, refined typography, and smooth hover pauses.
 */
export function ShipFeatures() {
  const { open: openQuote } = useQuote();

  return (
    <section
      id="features"
      className="bg-page py-[clamp(78px,12vh,150px)] overflow-hidden"
    >
      <Reveal>
        <header
          className={cx(
            revealItem,
            "max-w-[780px] mb-[clamp(36px,5vh,54px)] px-gut",
          )}
        >
          <p className={cx(label, "text-azure mb-3")}>
            Comprehensive Fleet Platform
          </p>
          <h2 className="type-display m-0 text-[clamp(28px,3.8vw,52px)] text-ink-text">
            Every capability, moving in{" "}
            <span className="text-azure">unison</span>
          </h2>
          <p className="mt-4 text-[clamp(15px,1.15vw,17.5px)] leading-[1.62] text-body-text">
            Ten purpose-built operational capabilities working continuously
            across our fleet. Hover over any card to pause and review
            specifications.
          </p>
        </header>

        {/* Dual-Tier Opposing Marquee Stage */}
        <div
          style={{ "--i": 1 } as React.CSSProperties}
          className={cx(
            revealItem,
            "relative overflow-hidden w-full py-2 space-y-6",
          )}
        >
          {/* Left and Right Edge Scrims for Smooth Edge Fading */}
          <div
            aria-hidden="true"
            className="pointer-events-none absolute inset-y-0 left-0 w-20 sm:w-44 bg-gradient-to-r from-page via-page/80 to-transparent z-10"
          />
          <div
            aria-hidden="true"
            className="pointer-events-none absolute inset-y-0 right-0 w-20 sm:w-44 bg-gradient-to-l from-page via-page/80 to-transparent z-10"
          />

          {/* Row 1: Scrolls Left */}
          <div className="flex w-max gap-6 animate-roll hover:[animation-play-state:paused] motion-reduce:animate-none">
            {[0, 1].map((copy) => (
              <div
                key={copy}
                className="flex shrink-0 gap-6"
                aria-hidden={copy === 1}
              >
                {ROW_1_FEATURES.map((item, idx) => (
                  <FeatureCard key={`${copy}-${idx}`} feature={item} />
                ))}
              </div>
            ))}
          </div>

          {/* Row 2: Scrolls Right */}
          <div className="flex w-max gap-6 animate-roll-reverse hover:[animation-play-state:paused] motion-reduce:animate-none">
            {[0, 1].map((copy) => (
              <div
                key={copy}
                className="flex shrink-0 gap-6"
                aria-hidden={copy === 1}
              >
                {ROW_2_FEATURES.map((item, idx) => (
                  <FeatureCard key={`${copy}-${idx}`} feature={item} />
                ))}
              </div>
            ))}
          </div>
        </div>

        {/* Bottom Conversion Action Bar */}
        <div
          style={{ "--i": 2 } as React.CSSProperties}
          className={cx(
            revealItem,
            "mt-12 flex flex-col items-center justify-center text-center px-gut",
          )}
        >
          <button
            type="button"
            onClick={openQuote}
            className={cx(
              btn,
              btnSolid,
              btnHero,
              "shadow-[0_8px_24px_-8px_rgba(11,143,203,0.5)]",
            )}
          >
            Get a Freight Quote
            <ArrowRight size={17} />
          </button>
          <p className="mt-3 text-xs text-soft-text font-mono">
            Direct enterprise dispatch:{" "}
            <a
              href="tel:+18004605071"
              className="text-azure font-semibold hover:underline"
            >
              (800) 460-5071
            </a>{" "}
            · Instant rate sheet &amp; TMS integration
          </p>
        </div>
      </Reveal>
    </section>
  );
}
